# **NUMPY ASSIGNMENT**

In [43]:
import numpy as np

In [ ]:
# Write a function so that the columns of the output matrix are powers of the input
# vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.

In [54]:
def mvan(vector, n ,increasing ):
  l=[]
  for i in range(n):
    row=[]
    for j in range(n):
      if(increasing ==True):
        row.append(vector[i]**j)
      else:
        row.append(vector[i]**(n-1-j))
    l.append(row)
 
  return np.array(l) 

In [55]:
print(mvan([1,2,3,4,5],5,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [56]:
print(mvan([1,2,3,4,5],5,True))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [ ]:
# Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [64]:
def moving_average(arr, window):
    start=0
    end=window-1
    while(end<len(arr)):
        average=0
        for i in range(start,end+1):
            average=average+arr[i]
        average= average/window
        print("y",start+1," = ",average,sep="")
        end=end+1
        start=start+1

In [65]:
arr=[10,20,30,40,50,60,70,80,90,100]
window=4
moving_average(arr, window)

y1 = 25.0
y2 = 35.0
y3 = 45.0
y4 = 55.0
y5 = 65.0
y6 = 75.0
y7 = 85.0


In [66]:
arr=[3 ,5 ,7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window=3
moving_average(arr,window)

y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
